### Post request: send name as param
POST http://localhost:8080/primeiraController/metodoComBodyParams
Content-Type: application/json

{
  "username": "Marcel"
}

### Post request: send with headers
POST http://localhost:8080/primeiraController/metodoComHeaders
Content-Type: application/json
name: Marcel (Header)

### Post request: send with headers
POST http://localhost:8080/primeiraController/metodoComListHeaders
Content-Type: application/json
name: Marcel (Header)
username: mgckdev
Authorization: 232323232323232323

### Get request: get username by id
GET http://localhost:8080/primeiraController/metodoResponseEntity/6

### Get request: component
GET http://localhost:8080/component/